import Head from "next/head";
// import Pro from '../pages/pro'
import Schedule from "../components/schedule";
import Team from "../components/team";

export default function Home() {
  return (
    <>
      <Head>
        <title>P&B</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <svg className="img_play"></svg>
        <svg className="img_illustration"></svg>
      </div>
      <div className="container">
        <svg className="img_group"></svg>
        <Schedule />
        <svg className="comand"></svg>
        <Team />
      </div>
    </>
  );
}
